export const listFood = [
  {
    id: 1,
    title: 'Ayam Cabe Garam',
    image: 'ayam_cabe_garam.jpg',
    inspired: 'Yulia Baltschun',
    link: 'https://www.instagram.com/yuliabaltschun',
    rating: 4,
  },
  {
    id: 2,
    title: 'Ayam mentega',
    image: 'ayam_mentega.JPG',
    inspired: 'Erisa',
    link: 'https://www.tiktok.com/@hi_erisa/video/7061843669480918299?_r=1&_t=8ZpnXT2g5jN',
    rating: 4,
  },
  {
    title: 'Ayam Tahu Kecap',
    image: 'ayam_tahu_kecap.JPG',
    inspired: 'Author',
    rating: 5,
  },
  {
    title: 'Beef Teriyaki with Egg Mayo',
    image: 'beef_teriyaki_egg_mayo.JPG',
    inspired: 'Author',
    rating: 5,
  },
  {
    title: 'Jamur Selimut',
    image: 'beef_teriyaki_jamur_enoki.JPG',
    inspired: 'Safira',
    link: 'https://vt.tiktok.com/ZS85rY9ff/',
    rating: 4,
  },
  {
    title: 'Chicken Creamy Mushroom',
    image: 'chicken_creamy_mushroom.JPG',
    inspired: 'Chef Arnold',
    link: 'https://vt.tiktok.com/ZS85rRkKE/',
    rating: 4,
  },
  {
    title: 'Chicken Curry',
    image: 'chicken_curry.JPG',
    inspired: 'Author',
    rating: 3,
  },
  {
    title: 'Chicken Deopbab',
    image: 'chicken_dongbap.PNG',
    inspired: 'Michele Alex',
    link: 'https://vt.tiktok.com/ZS85r5Umq/',
    rating: 5,
  },
  {
    title: 'Ayam Jamur Mentega',
    image: 'chicken_jamur.jpg',
    inspired: 'Aza Kitchen',
    link: 'https://vt.tiktok.com/ZS85rHFtL/',
    rating: 5,
  },
  {
    title: 'Chicken Mayonaise',
    image: 'chicken_mayonaise.JPG',
    inspired: 'Dyon Banggara',
    link: 'https://vt.tiktok.com/ZS85rtuwD/',
    rating: 5,
  },
  {
    title: 'Chicken Roasted Indomie',
    image: 'chicken_roasted_indomie.JPG',
    inspired: 'Author',
    rating: 4,
  },
  {
    title: 'Egg Droup Soup',
    image: 'egg_droup_soup.JPG',
    inspired: 'Novi Susanto',
    link: 'https://vt.tiktok.com/ZS85rgmwY/',
    rating: 4,
  },
  {
    title: 'Gyoza',
    image: 'gyoza.JPG',
    inspired: 'Agiel',
    link: 'https://vt.tiktok.com/ZS85rgP1f/',
    rating: 5,
  },
  {
    title: 'Kimchi Jjigae',
    image: 'kimchi_jiggae.JPG',
    inspired: 'Michele Alex',
    link: 'https://vt.tiktok.com/ZS85rgxr7/',
    rating: 5,
  },
  {
    title: 'Swedish Meatballs IKEA',
    image: 'meatball_ikea.JPG',
    inspired: 'Devina Hermawan',
    link: 'https://vt.tiktok.com/ZS85rb8JS/',
    rating: 4,
  },
  {
    title: 'Nasi Telor Mentai',
    image: 'nasi_telor_mentai.JPG',
    inspired: 'Mba Nana Eats',
    link: 'https://vt.tiktok.com/ZS85rUUj4/',
    rating: 5,
  },
  {
    title: 'Sandwich Apple Milky',
    image: 'roti_apple.jpg',
    inspired: 'Author',
    rating: 5,
  },
  {
    title: 'Sapo tahu Jamur',
    image: 'sapo_tahu_jamur.PNG',
    inspired: 'Adeline',
    link: 'https://vt.tiktok.com/ZS85rqVhV/',
    rating: 5,
  },
  {
    title: 'Sawi Korea',
    image: 'sawi_merah_korea.JPG',
    inspired: 'Mutia',
    link: 'https://vt.tiktok.com/ZS85rmter/',
    rating: 4,
  },
  {
    title: 'Scallion Oil Chicken Rice',
    image: 'scallion_oil_chicken.JPG',
    inspired: 'Aza Kitchen',
    link: 'https://vt.tiktok.com/ZS85rGFMw/',
    rating: 4,
  },
  {
    title: 'Soup Wonton',
    image: 'soup_wonton.JPG',
    inspired: 'Apriscay',
    link: 'https://vt.tiktok.com/ZS85rs82X/',
    rating: 5,
  },
  {
    title: 'Spicy Butter Milk Chicken',
    image: 'spicy_butter_milky_chicken.JPEG',
    inspired: 'Martin Natadipraja',
    link: 'https://vt.tiktok.com/ZS85rQe3w/',
    rating: 5,
  },
  {
    title: 'Sweet Garlic Korean Chicken',
    image: 'sweet_garlic_korean_chicken.JPG',
    inspired: 'Christie',
    link: 'https://vt.tiktok.com/ZS85rbuq7/',
    rating: 4,
  },
  {
    title: 'Tahu Cabe Garam',
    image: 'tahu_cabe_garam.JPG',
    inspired: 'Author',
    rating: 4,
  },
  {
    title: 'Tahu Saus Merah',
    image: 'tahu_saos_merah.PNG',
    inspired: 'Author',
    rating: 4,
  },
  {
    title: 'Telor Kecap Menado',
    image: 'telor_kecap.JPG',
    inspired: 'Mba Mida',
    link: 'https://vt.tiktok.com/ZS85rq4sS/',
    rating: 5,
  },

  // {
  //   title: '',
  //   image : '',
  //   rating:
  // },
];
